### ISSUE TITLE
Ideen für Funktion d) 

### ISSUE THREAD

**Issue by smlemons** [SchneckenerR/wissenschaftliches-arbeiten#1]
Danke @321Svetlana für den Code funktion1.R ! Du hattest gefragt, welche Koeffizienten wir noch berechnen könnten bei der Funktion für bivariate Variablen (metrisch & dichotom). Deswegen habe ich mal einen Issue dafür aufgemacht :)

**Comment by smlemons** [comment]
Vielleicht könnte man zwei Tabellen ausgeben lassen, jeweils für die beiden Merkmalsausprägungen der dichotomen Variable?

**Comment by 321Svetlana** [comment]
An sich ein guter Vorschlag @smlemons ! Angenommen wir lassen Mittelwert und/oder Median als Kennzahlen für beide Fälle 0 und 1 ausgeben (Ausprägungen der dichotomen Variable), wie könnte man daraus Schlussfolgerungen auf den Zusammenhang ziehen? Wie könnte man das Ergebnis dann interpretieren?

**Comment by 321Svetlana** [comment]
Ach jetzt ist mir das klar. Man kann sagen, dass bei den Variablen mit 0 z.B. der Mittelwert kleiner ist als bei Variablen mit 1 als Ausprägung der dichotomen Variable. Dann geht es doch ganz gut von der Interpretation.

Als mögliche Kennzahlen zum Vergleich der beiden Ausprägungen würde ich dann nur den Mittelwert ausgeben lassen. Dann braucht man keine ganzen zwei Tabellen, sondern nur zwei zusätzliche Werte auszugeben.

**Comment by smlemons** [comment]
Perfekt, danke dir fürs Ändern :)
